name: Alexanderson Bola√±o
favicon: null
layout_spectrum: 0.09917423687875271
typography_spectrum: 0.08335384796373546
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7106952934991568
  lightness: 0.8241940168663859
  saturation: 0.3093509809114039
  rhythmicContrast: 0.6527489740401506
purpose: []
